changesetIgnorePatterns:
    - "**/*.tsbuildinfo"

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

enableScripts: false

enableTelemetry: false

nodeLinker: pnp

npmMinimalAgeGate: 30d

preferInteractive: true

progressBarStyle: patrick
